package com.example.graduation1.domain.models

sealed class AppPages(val route: String) {
    object OnBoardingTabs : AppPages("onBoardingTabs")
    object SignUp : AppPages("signUpScreen")
    object Login : AppPages("loginScreen")
    object CreateAccount : AppPages("createAccountScreen")
    object Post : AppPages("postScreen")
    object MyProfile : AppPages("myProfileScreen")
    object MyProfileDetails : AppPages("myProfileDetailsScreen")
    object OtherUsersProfile : AppPages("otherUsersProfileScreen")
    object EditProfile : AppPages("editProfileScreen")
    object StartScreen : AppPages("startScreen")
    object ChatbotStart : AppPages("chatbotStartScreen")
    object Chatbot : AppPages("chatbotScreen")
    object Notification : AppPages("notificationScreen")
    object NotificationSettings : AppPages("notificationSettingsScreen")
    object Settings : AppPages("settingScreen")
    object Favourite : AppPages("FavouriteScreen")
    object Saved : AppPages("savedScreen")
    object Language : AppPages("LanguageScreen")
    object Location : AppPages("LocationScreen")
    object Subscription : AppPages("SubscriptionScreen")
    object ReportTabs : AppPages("reportTabs")
    object Password : AppPages("PasswordScreen")
    object AboutApplication : AppPages("AboutApplicationScreen")
    object FAQ : AppPages("FAQScreen")
    object MyRooms : AppPages("MyRoomsScreen")
    object InRooms : AppPages("inRoomsScreen")
    object Messaging : AppPages("messagingScreen")
}